import './globals.css'
import type {Metadata} from 'next'
import {Fira_Sans} from 'next/font/google'
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import {FC} from "react";
import {getCookie, hasCookie} from "cookies-next";

const firaSans = Fira_Sans({subsets: ["cyrillic", "latin"], weight: "400"})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



const RootLayout: FC<Props> = ({children}) => {

  return (
    <html lang="en">
      <body className={firaSans.className}>
        <Header/>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  )
}

interface Props {
  children: React.ReactNode,
}

export default RootLayout